Parameters:
  App:
    Type: String
  Env:
    Type: String

Resources:
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${App}-${Env}-scheduler-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:UpdateService
                  #- rds:StopDBInstance
                  #- rds:StartDBInstance
                Resource: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${App}-${Env}/${App}-${Env}-api

  StopResourcesRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${App}-${Env}-stop-resources
      Description: "Stop resources during off-hours"
      ScheduleExpression: "cron(10 17 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "Asia/Tokyo"
      State: ENABLED
      Targets:
        - Id: StopECSService
          Arn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${App}-${Env}
          RoleArn: !GetAtt SchedulerRole.Arn
          EcsParameters:
            TaskCount: 0
            TaskDefinitionArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${App}-${Env}-api

  StartResourcesRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${App}-${Env}-start-resources
      Description: "Start resources during work hours"
      ScheduleExpression: "cron(0 12 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "Asia/Tokyo"
      State: ENABLED
      Targets:
        - Id: StartECSService
          Arn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${App}-${Env}
          RoleArn: !GetAtt SchedulerRole.Arn
          EcsParameters:
            TaskCount: 1
            TaskDefinitionArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${App}-${Env}-api
